<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>XIVMitigationPlugin</AssemblyName>
    <RootNamespace>XIVMitigationPlugin</RootNamespace>
    <Version>1.0.0</Version>
    <PackageProjectUrl>https://github.com/Maateria/XIVMitigationPlugin</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Manifest Dalamud — doit porter le même nom que l'AssemblyName -->
    <Content Include="XIVMitigationPlugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
